# Generated by Django 5.1.4 on 2025-02-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nishatiflex', '0002_alter_lukutoken_purchase_date_lukuamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterinfo',
            name='average_days_per_token',
        ),
        migrations.RemoveField(
            model_name='meterinfo',
            name='phone_number',
        ),
    ]
