# Generated by Django 5.1.4 on 2025-02-16 13:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nishatiflex', '0003_remove_meterinfo_average_days_per_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lukuamount',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lukutoken',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
