# Generated by Django 5.1.4 on 2025-02-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nishatiflex', '0005_energypurchase_userprofile_delete_lukuamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='energypurchase',
            name='daily_consumption',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='energypurchase',
            name='remaining_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='energypurchase',
            name='units',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
