# Generated by Django 5.1.4 on 2025-02-22 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nishatiflex', '0006_energypurchase_daily_consumption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnergyPurchase',
            new_name='EnergyPurchased',
        ),
    ]
