# Generated by Django 5.1.4 on 2025-02-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nishatiflex', '0007_rename_energypurchase_energypurchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='energypurchased',
            name='remaining_energy',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
