# Generated by Django 5.1.4 on 2025-02-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nishatiflex', '0008_energypurchased_remaining_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energypurchased',
            name='remaining_days',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
