# Generated by Django 5.1.4 on 2025-03-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nishatiflex', '0009_alter_energypurchased_remaining_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LukuToken',
        ),
    ]
