# Generated by Django 5.1.4 on 2025-03-08 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nishatiflex', '0009_alter_energypurchased_remaining_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('remainder', 'Remainder'), ('alert', 'Alert'), ('update', 'Update')], max_length=100)),
                ('energy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nishatiflex.energypurchased')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
