# Generated by Django 5.1.4 on 2025-03-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='energy',
        ),
    ]
